#!/bin/bash 

. /usr/local/lib/iptables-utils/allow_server.sh

echo "Protocol:"
read -r PROTOCOL
echo "Interface:" 
read -r INTERFACE
echo "Port:"
read -r PORT

allow_server "$PROTOCOL" "$INTERFACE" "$PORT"