#!/bin/bash 
. /usr/local/lib/iptables_utils/allow_forward_to_server.sh

echo "running as"
whoami
echo "running as"

allow_forward_to_server "$1" "$2" "$3" "$4" "$5" "$6" "$7"
iptables-save > /etc/iptables/rules.v4